bgdict/urls.py
from django.conf.urls import url
from django.contrib import admin

from ui.views import index, favorite

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
    url(r'^favorite/([0-9]*)/$', favorite, name='favorite')
]

ui/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ui/', include('ui.urls'),
]

ui/models.py
from django.db import models
from django.urls import reverse
from django.utils.html import mark_safe


class Word(models.Model):
    word = models.CharField(max_length=255)
    trans_html = models.TextField()
    trans_text = models.TextField()

    last_seen = models.DateTimeField(null=True, blank=True)
    views = models.PositiveIntegerField(default=0)
    favorite = models.BooleanField(default=False)

    def to_html(self):
        html = '<a class="favorite" style="color: #f00; float: right;" href="%s">' % reverse('favorite', args=(self.pk,))
        if hasattr(self, 'rank'):
            html += '%0.1f' %  self.rank + ' '
        if self.favorite:
            html += '♥'
        else:
            html += '♡'
        html += '</a>'
        html += self.trans_html
        return mark_safe(html)

ui/views.py
from datetime import datetime
import unicodedata
from urllib.parse import quote

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.contrib.postgres.search import SearchQuery, SearchVector, SearchRank
from django import forms

from .models import Word


class SearchForm(forms.Form):
    search = forms.CharField(max_length=1024)



# based on https://stackoverflow.com/questions/35942129/remove-accent-marks-from-characters-while-preserving-other-diacritics
ACCENT_MAPPING = {
    'а́': 'а',
    'а̀': 'а',
    'е́': 'е',
    'ѐ': 'е',
    'и́': 'и',
    'ѝ': 'и',
    'о́': 'о',
    'о̀': 'о',
    'у́': 'у',
    'у̀': 'у',
    'ы́': 'ы',
    'ы̀': 'ы',
    'э́': 'э',
    'э̀': 'э',
    'ю́': 'ю',
    '̀ю': 'ю',
    'я́́': 'я',
    'я̀': 'я',
}
ACCENT_MAPPING = {unicodedata.normalize('NFKC', i): j for i, j in ACCENT_MAPPING.items()}


def unaccentify(s):
    source = unicodedata.normalize('NFKC', s)
    for old, new in ACCENT_MAPPING.items():
        source = source.replace(old, new)
    return source


def index(request):
    form = SearchForm(request.GET)
    full = request.GET.get('full') != 'false'
    nostat = request.GET.get('nostat') == 'true'

    context = {
        'form': form,
        'full': full
    }

    if form.is_valid():
        search = unaccentify(form.cleaned_data['search'])
        vectors = SearchVector('trans_text', config='bulgarian') + SearchVector('word', config='bulgarian')
        query = SearchQuery(search, config='bulgarian')
        words = Word.objects.annotate(rank=SearchRank(vectors, query)).filter(rank__gt=0.05).order_by('-rank')[:5]

        if len(words) == 0:
            words = Word.objects.annotate(rank=SearchRank(vectors, query)).exclude(rank=0).order_by('-rank')[:5]

        if len(words) == 0:
            words = Word.objects.filter(trans_text__iregex=r'\y%s\y' % search)[:5]

        count = words.count()
        if count:
            msg = '%i match.' % count
        else:
            msg = 'No result.'

        if not nostat:
            for w in words:
                if w.last_seen is None or w.last_seen.date() != datetime.today():
                    w.views += 1
                w.last_seen = timezone.now()
                w.save()

        if unicodedata.name(search.strip()[0]).startswith('CYRILLIC'):
            dict_link = 'https://www.dict.com/?t=bg&set=_bgen&w='
        else:
            dict_link = 'https://www.dict.com/?t=bg&set=_enbg&w='
        dict_link += quote(search)

        context.update({
            'results': words,
            'msg': msg,
            'search': search,
            'dict_link': dict_link
        })
    else:
        last_seen = Word.objects.exclude(last_seen__isnull=True).order_by('-last_seen')[:5]
        top = Word.objects.exclude(views=0).order_by('-views', '-last_seen')[:5]
        favorite = Word.objects.exclude(last_seen__isnull=True).filter(favorite=True).order_by('-last_seen')[:5]
        context['panels'] = [{
            'title': 'Last seen',
            'words': last_seen
        }, {
            'title': 'Favorite',
            'words': favorite
        }, {
            'title': 'Top',
            'words': top
        }]

    return render(request, 'ui/index.html', context)


def favorite(request, fav_id):
    w = get_object_or_404(Word, pk=fav_id)
    w.favorite = not w.favorite
    w.save()
    
    to = request.META.get('HTTP_REFERER', None)
    if to:
        if not 'nostat=true' in to:
            if '?' in to:
                to += '&'
            else:
                to += '?'
            to += 'nostat=true'
    else:
        to = '/'
    return redirect(to)

ui/templates/ui/index.html
<!DOCTYPE html>
<html>
<head>
    <title>BGDict{% if search %} - {{ search }}{% endif %}</title>
    <link href="/static/css/default.css" rel="stylesheet" type="text/css">
    <link href="/static/css/night.css" rel="alternate stylesheet" title="Night" type="text/css">

{% if full %}
    <!-- jQuery 3.1.0 -->

    <script src="/static/jquery/jquery.min.js"></script>
    
    <!-- jQuery UI theme or Bootstrap (optional, if you create a custom theme) 1.12.0 -->
    <link href="/static/jquery/jquery-ui.css" rel="stylesheet">
    <!-- <link href="/statc/kbd/css/bootstrap.min.css" rel="stylesheet"> -->
    
    <!-- jQuery UI position utility (optional, if you position the keyboard yourself) -->
    <script src="/static/jquery/jquery-ui.min.js"></script>
    
    <!-- keyboard widget css & script -->
    <link href="/static/kbd/css/keyboard.min.css" rel="stylesheet">
    <script src="/static/kbd/js/jquery.keyboard.js"></script>
    <!-- <script src="/static/kbd/layouts/keyboard-layouts-greywyvern.min.js"></script> -->
    
    <!-- css for the preview keyset extension -->
    <link href="/static/kbd/css/keyboard-previewkeyset.min.css" rel="stylesheet">
    <script type="application/javascript">
        $(document).ready(function () {
            let urlParams = new URLSearchParams(window.location.search);
            if (urlParams.has('search') && $('#id_search').length) {
                $('#id_search').val(urlParams.get('search'));
            }

            $('#id_search').keyboard({
                layout: 'custom',
                //layout: 'bg-ph',
                //layout: 'bg',
                customLayout: {
                    normal: ["у е и ш щ к с д з ц","ь я а о ж г т н В м ч","Ю й ъ э ф х п р л б","{space} {b}"]
                },
                usePreview: false,
                openOn: '',
                appendTo: '#formdiv',
                autoAccept: true,
                display: {
                    'accept': '',
                    'tab': ''
                }
            });
            $('button').click(function(){
                $('#id_search').getkeyboard().reveal();
                return false;
            });
        });
    </script>
{% else %}
    <script type="application/javascript">
        window.onload = function() {
            if(!window.location.hash) {
                window.location = window.location + '#loaded';
                window.location.reload();
                }
            }
    </script>
{% endif %}
</head>
<body>

{% if full %}
<div id="formdiv">
    <form>
        <input type="text" name="search" maxlength="1024" required="" id="id_search">
        <input type="submit" value="Search">
        <button value="Keyboard">🇧🇬</button>
        <a href="/">Clear</a>
    </form>
</div>
<hr>
{% endif %}

{{ msg }}{% if dict_link %} - <a href="{{ dict_link }}">Dict.com</a>{% endif %}
<hr>
{% if results %}
    <div style="width: 50%;">
        {% for r in results %}
            {{ r.to_html }}
            <hr>
        {% endfor %}
    </div>
{% endif %}

{% if panels %}
    {% for panel in panels %}
        <div style="padding: 10px; float: left; width: 30%; {% if forloop.counter0 == 1 %}background-color: #e0f0f0; height: 100%;{% endif %}">
            {{ panel.title }}
            <hr>
            {% for w in panel.words %}
                {{ w.to_html }}
                <hr>
            {% endfor %}
        </div>
    {% endfor %}
{% endif %}

</body>
</html>